### ISSUE TITLE
Error on all fxns

### ISSUE THREAD

**Issue by sckott** [WestleyArgentum/OpenSecrets.jl#3]
For example, I'm getting:

``` julia
pac_contribs = OpenSecrets.pacs_to_candidates(12)
```

``` julia
ERROR: opening file pacs12.txt: No such file or directory
 in systemerror at error.jl:39
 in open at iostream.jl:113
 in open at iostream.jl:125
 in pacs_to_candidates at /Users/sacmac/.julia/v0.3/OpenSecrets/src/data_loading.jl:12
```

**Comment by WestleyArgentum** [comment]
Hey! I should probably call more attention to this in the readme, but the data isn't bundled with this repo (both because it's too big for github and because I'm not sure Open Secrets would be super pleased).

I tried to explain here: https://github.com/WestleyArgentum/OpenSecrets.jl/tree/master/data

Basically, if you download the zip bundles from open secrets, extract them, and put them in `/Users/sacmac/.julia/v0.3/OpenSecrets/data/`it should work. You can also keep them somewhere else and use `detect_data_sources` function here: https://github.com/WestleyArgentum/OpenSecrets.jl#detecting-data-sources

**Comment by sckott** [comment]
ah, ok, thanks, I just figured you were using the API https://www.opensecrets.org/resources/create/apis.php
